# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    slack(
      slack_url: "https://hooks.slack.com/services/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"
    )
  end

  desc "Send Notice Slack"
  lane :beta  do
    # add actions here: https://docs.fastlane.tools/actions

  end

  after_all do
    slack(
      slack_url: "https://hooks.slack.com/services/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",
      message: "RxBookManager-iOSをデプロイしました。"
    )
  end

  error do |lane, exception|
     slack(
       slack_url: "https://hooks.slack.com/services/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",
       message: exception.message,
       success: false
     )
  end
end

